openapi: 3.0.0
info:
  description: EPMS API
  version: '1.0'
  title: gui
servers:
  - url: /api/v1.0


paths:
  /suggestions:
    post:
      tags:
        - suggestions
      summary: get suggestions for the given executable bpmn
      operationId: postSuggestions
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                processModel:
                  type: string
                  format: binary
      responses:
        200:
          description: ok
        404:
          description: error


