/* tslint:disable */
/* eslint-disable */
/**
 * gui
 * EPMS API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EffectedElement
 */
export interface EffectedElement {
    /**
     * 
     * @type {string}
     * @memberof EffectedElement
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof EffectedElement
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EffectedElement
     */
    type?: EffectedElementTypeEnum;
}

/**
* @export
* @enum {string}
*/
export enum EffectedElementTypeEnum {
    Task = 'Task',
    Event = 'Event'
}

export function EffectedElementFromJSON(json: any): EffectedElement {
    return EffectedElementFromJSONTyped(json, false);
}

export function EffectedElementFromJSONTyped(json: any, ignoreDiscriminator: boolean): EffectedElement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function EffectedElementToJSON(value?: EffectedElement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'type': value.type,
    };
}

